#include "Localization.hpp"

#include <unordered_map>

namespace YimMenu
{
	static const std::unordered_map<std::string, std::string>& GetLocalizationMap()
	{
		static const std::unordered_map<std::string, std::string> map = {
			// ================= COMMAND LABELS =================
			{"2ND", "2. Kişi"},
			{"Access Code", "Erişim Kodu"},
			{"Actual Take", "Güncel Pay"},
			{"Aim For Head", "Kafaya Nişan Al"},
			{"Aimbot", "Aimbot"},
			{"Allow Gender Change", "Cinsiyet Değişimine İzin Ver"},
			{"Allow Hats In Vehicles", "Araçlarda Şapka Serbest"},
			{"Allow MP Vehicles in SP", "MP Araçlarına Hikayede İzin Ver"},
			{"Alpha Mail Disguise", "Alpha Mail Kılığı"},
			{"Animal", "Hayvan"},
			{"Annihilator (Prep)", "Annihilator (Hazırlık)"},
			{"Annihilator Stealth", "Annihilator Gizli"},
			{"Anonymous Bounty", "Anonim Ödül"},
			{"Approach", "Yaklaşım"},
			{"Armored Caracara", "Zırhlı Caracara"},
			{"Auto Teleport to Waypoint", "Noktaya Otomatik Işınla"},
			{"Auto-Enter PC Access Code", "PC Erişim Kodunu Otomatik Gir"},
			{"Beat Time Trial", "Süre Denemesini Geç"},
			{"Blackscreen", "Siyah Ekran"},
			{"Boost Behavior", "Boost Davranışı"},
			{"Bounty Amount", "Ödül Miktarı"},
			{"Bring", "Getir"},
			{"Bring All Objects", "Tüm Nesneleri Getir"},
			{"Bring All Peds", "Tüm PED'leri Getir"},
			{"Bring All Vehicles", "Tüm Araçları Getir"},
			{"Buried Stash", "Gömülü İstif"},
			{"Business", "İşletme"},
			{"Bypass Casino Restrictions", "Casino Kısıtlamalarını Aş"},
			{"Call Mechanic", "Tamirci Çağır"},
			{"Caracara (Prep)", "Caracara (Hazırlık)"},
			{"CEO Kick", "CEO At"},
			{"Change Appearance For Free", "Ücretsiz Görünüm Değiştir"},
			{"Chat", "Sohbet"},
			{"Claim Safe Earnings", "Kasa Kazancını Al"},
			{"Clear Chat", "Sohbeti Temizle"},
			{"Clear Damage", "Hasarı Temizle"},
			{"Clear Wanted", "Aranmayı Temizle"},
			{"Collect Buried Stash", "Gömülü İstifi Topla"},
			{"Collect Golden Clover", "Altın Yoncayı Topla"},
			{"Collect G's Cache", "G'nin Önbelleğini Topla"},
			{"Collect Hidden Cache", "Gizli Önbelleği Topla"},
			{"Collect Product", "Ürünü Topla"},
			{"Collect Shipwreck", "Enkazı Topla"},
			{"Collect Treasure Chest", "Hazine Sandığını Topla"},
			{"Complete All Challenges", "Tüm Görevleri Tamamla"},
			{"Complete Skydive", "Paraşüt Atlayışını Tamamla"},
			{"Cops Dispatch", "Polis Sevkiyatı"},
			{"Custom Weapon", "Özel Silah"},
			{"Cut Glass", "Camı Kes"},
			{"Cut Sewer", "Kanalizasyonu Kes"},
			{"Delete All Objects", "Tüm Nesneleri Sil"},
			{"Delete All Peds", "Tüm PED'leri Sil"},
			{"Delete All Vehicles", "Tüm Araçları Sil"},
			{"Delete Vehicle", "Aracı Sil"},
			{"Deliver Next Exotic Exports Vehicle", "Sonraki Egzotik İhracat Aracını Teslim Et"},
			{"Despawn Personal Vehicle", "Kişisel Aracı Kaldır"},
			{"Difficulty", "Zorluk"},
			{"Disable Action Mode", "Aksiyon Modunu Kapat"},
			{"Disable Critical Hits", "Kritik Vuruşları Kapat"},
			{"Disable Death Barriers", "Ölüm Bariyerlerini Kapat"},
			{"Disable Laser Grid", "Lazer Izgarasını Kapat"},
			{"Driver", "Şoför"},
			{"Dump Data Hash", "Veri Hash'ini Dök"},
			{"EMP Charges", "EMP Yükleri"},
			{"EMP Charges (Prep)", "EMP Yükleri (Hazırlık)"},
			{"Enable All DLC Vehicles", "Tüm DLC Araçlarını Etkinleştir"},
			{"Enable Buried Stashes in LS", "LS'de Gömülü İstifleri Etkinleştir"},
			{"Enable Creator Dev Mode", "Yaratıcı Geliştirici Modunu Etkinleştir"},
			{"Enable Only if Weapon is Out", "Sadece Silah Eldeyken Etkinleştir"},
			{"Enable Special Abilities in MP", "MP'de Özel Yetenekleri Etkinleştir"},
			{"Enable Treasure Chests in LS", "LS'de Hazine Sandıklarını Etkinleştir"},
			{"Enter Last Vehicle", "Son Araca Bin"},
			{"Enter Stash House Safe Code", "Stash House Kasa Kodunu Gir"},
			{"Explode", "Patlat"},
			{"Explosive Ammo", "Patlayıcı Mermi"},
			{"Fast Join", "Hızlı Katılma"},
			{"Fill Inventory", "Envanteri Doldur"},
			{"Fix All Vehicles", "Tüm Araçları Onar"},
			{"Force Ready", "Hazır Olmaya Zorla"},
			{"Force Script Host", "Script Host Olmaya Zorla"},
			{"Force Thunder", "Gök Gürültüsünü Zorla"},
			{"Force Weather", "Havayı Zorla"},
			{"Format Money", "Parayı Biçimlendir"},
			{"Freecam", "Serbest Kamera"},
			{"Freecam Speed", "Serbest Kamera Hızı"},
			{"Freemode State Kick", "Freemode Durum Atması"},
			{"Freeze Time", "Zamanı Dondur"},
			{"Freeze Wanted", "Aranmayı Dondur"},
			{"Give All Weapons", "Tüm Silahları Ver"},
			{"Give Max Ammo", "Max Mermi Ver"},
			{"Give Weapons", "Silah Ver"},
			{"Glass Cutter", "Cam Kesici"},
			{"Glass Cutter (Prep)", "Cam Kesici (Hazırlık)"},
			{"God Mode", "Tanrı Modu"},
			{"Guard Routes", "Devriye Rotaları"},
			{"Guard Routes (Prep)", "Devriye Rotaları (Hazırlık)"},
			{"Guard Shipments", "Sevkiyatları Koru"},
			{"Gunman", "Silahlı Adam"},
			{"Hacker", "Hacker"},
			{"Hacking Device", "Hack Cihazı"},
			{"Harass Players", "Oyuncuları Rahatsız Et"},
			{"Hazmat Suit", "Koruyucu Takım"},
			{"Heal", "İyileştir"},
			{"Hidden Cache", "Gizli Önbellek"},
			{"Horn Boost", "Korna Boostu"},
			{"Host Kick", "Host Atması"},
			{"Hour", "Saat"},
			{"INF", "SINIRSIZ"},
			{"Infinite Ammo", "Sınırsız Mermi"},
			{"Infinite Boundary", "Sınırsız Sınır"},
			{"Infinite Clip", "Sınırsız Şarjör"},
			{"Infinite Parachutes", "Sınırsız Paraşüt"},
			{"Infinite Special Ability", "Sınırsız Özel Yetenek"},
			{"Instant Finish", "Anında Bitir"},
			{"Instant Finish (Act: III)", "Anında Bitir (Perde: III)"},
			{"Instant Finish (Pacific)", "Anında Bitir (Pacific)"},
			{"Invisibility", "Görünmezlik"},
			{"IPL", "IPL"},
			{"Join Session", "Oturuma Katıl"},
			{"Join Session Type", "Katılınacak Oturum Türü"},
			{"Join YimMenu-only Sessions", "Sadece YimMenu Oturumlarına Katıl"},
			{"Keep Player Clean", "Oyuncuyu Temiz Tut"},
			{"Keep Vehicle Fixed", "Aracı Sağlam Tut"},
			{"Kill", "Öldür"},
			{"Kill All Enemies", "Tüm Düşmanları Öldür"},
			{"Kill All Peds", "Tüm PED'leri Öldür"},
			{"Launch Entity on Release", "Bırakınca Varlığı Fırlat"},
			{"Load IPL", "IPL Yükle"},
			{"Locally Visible", "Yerel Olarak Görünür"},
			{"Lower Vehicle Stance", "Araç Yüksekliğini Düşür"},
			{"LS Tag", "LS Etiketi"},
			{"Manchez", "Manchez"},
			{"Manchez (Prep)", "Manchez (Hazırlık)"},
			{"Manipulate Rig Slot Machines", "Slot Makinelerini Kullan"},
			{"Matchmaking Region", "Eşleşme Bölgesi"},
			{"Minute", "Dakika"},
			{"Mobile Radio", "Mobil Radyo"},
			{"Modify Boost Behavior", "Boost Davranışını Değiştir"},
			{"Move Rate Override", "Hareket Hızı Geçersiz Kılma"},
			{"Never Wanted", "Asla Aranma"},
			{"No Change Appearance Cooldown", "Görünüm Değiştirme Beklemesi Yok"},
			{"No Clip", "NoClip"},
			{"No Idle Kick", "Boşta Atma Yok"},
			{"No Ragdoll", "Ragdoll Yok"},
			{"Noclip Speed", "NoClip Hızı"},
			{"Null Function Kick", "Null Fonksiyon Atması"},
			{"Object Model", "Nesne Modeli"},
			{"Off The Radar", "Radardan Gizlen"},
			{"Open Gun Locker", "Silah Dolabını Aç"},
			{"Open Street Dealer Menu", "Sokak Satıcısı Menüsünü Aç"},
			{"Open Wardrobe", "Gardırobu Aç"},
			{"Override RP Multiplier", "RP Çarpanını Geçersiz Kıl"},
			{"Paint Gun Color", "Boya Tabancası Rengi"},
			{"Pause Game", "Oyunu Durdur"},
			{"Ped Model", "PED Modeli"},
			{"Peds Ignore", "PED'ler Yok Sayar"},
			{"Permadeath", "Kalıcı Ölüm"},
			{"Photograph Animal", "Hayvanı Fotoğrafla"},
			{"Play All Missions Solo", "Tüm Görevleri Tek Başına Oyna"},
			{"Player 1", "Oyuncu 1"},
			{"Player 2", "Oyuncu 2"},
			{"Player 3", "Oyuncu 3"},
			{"Player 4", "Oyuncu 4"},
			{"Player Teleport Coords", "Oyuncu Işınlama Koordinatları"},
			{"Points of Interest", "İlgi Noktaları"},
			{"Potential Take", "Potansiyel Pay"},
			{"Power Drills", "Güç Matkapları"},
			{"Power Drills (Prep)", "Güç Matkapları (Hazırlık)"},
			{"Primary Target", "Birincil Hedef"},
			{"Primary Target Value", "Birincil Hedef Değeri"},
			{"Product", "Ürün"},
			{"Rainbow Color", "Gökkuşağı Rengi"},
			{"Rainbow Color Speed", "Gökkuşağı Renk Hızı"},
			{"Rainbow Color Style", "Gökkuşağı Renk Stili"},
			{"Rapid Fire", "Seri Ateş"},
			{"Remove LSC Restrictions", "LSC Kısıtlamalarını Kaldır"},
			{"Repair Vehicle", "Aracı Onar"},
			{"Request Personal Vehicle", "Kişisel Aracı Çağır"},
			{"Reset All Activities", "Tüm Aktiviteleri Sıfırla"},
			{"Riot Mode", "İsyan Modu"},
			{"RP Multiplier Input", "RP Çarpanı Girişi"},
			{"Run/Sprint/Swim Multiplier", "Koş/Koşuştur/Yüz Çarpanı"},
			{"Save Personal Vehicle", "Kişisel Aracı Kaydet"},
			{"Scope Out", "İncele"},
			{"Script Host Kick", "Script Host Atması"},
			{"Seatbelt", "Emniyet Kemeri"},
			{"Second", "Saniye"},
			{"Secondary Take Value", "İkincil Pay Değeri"},
			{"Secondary Targets", "İkincil Hedefler"},
			{"Select Heist", "Soygun Seç"},
			{"Send Gooch", "Gooch Gönder"},
			{"Send Phantom Car", "Hayalet Araç Gönder"},
			{"Send Sext", "Sext Gönder"},
			{"Send to Interior", "İç Mekâna Gönder"},
			{"Send to Interior Index", "İç Mekân İndeksine Gönder"},
			{"Send to Property", "Mülke Gönder"},
			{"Send to Property Index", "Mülk İndeksine Gönder"},
			{"Set Actual Take", "Güncel Payı Ayarla"},
			{"Set All Activities Completed", "Tüm Aktiviteleri Tamamlanmış Yap"},
			{"Set Bounty", "Ödül Koy"},
			{"Set Cuts", "Payları Ayarla"},
			{"Set Potential Take", "Potansiyel Payı Ayarla"},
			{"Set Primary Target Value", "Birincil Hedef Değerini Ayarla"},
			{"Set Secondary Take Value", "İkincil Pay Değerini Ayarla"},
			{"Set Time", "Zamanı Ayarla"},
			{"Set Wanted", "Aranmayı Ayarla"},
			{"Set Weather", "Havayı Ayarla"},
			{"Setup", "Kurulum"},
			{"Silence Phone Calls", "Telefon Aramalarını Sustur"},
			{"Skip Conversation", "Konuşmayı Atla"},
			{"Skip Cutscene", "Sahneyi Atla"},
			{"Skip Data Crack", "Veri Kırma Mini Oyununu Atla"},
			{"Skip Drilling", "Delmeyi Atla"},
			{"Skip Fingerprint Hack", "Parmak İzi Hack'ini Atla"},
			{"Skip Hacking", "Hack'i Atla"},
			{"Skip Signal Nodes", "Sinyal Düğümlerini Atla"},
			{"Skip Swiping", "Kart Çekmeyi Atla"},
			{"Skydive", "Paraşüt Atlayışı"},
			{"Solo Mantrap", "Tek Başına Mantrap"},
			{"Spam Killfeed", "Killfeed Spamla"},
			{"Spawn Animal", "Hayvan Doğur"},
			{"Spawn Object", "Nesne Doğur"},
			{"Spawn Ped", "PED Doğur"},
			{"Special Ability in MP", "MP'de Özel Yetenek"},
			{"Spectate", "İzle"},
			{"Speedometer", "Hız Göstergesi"},
			{"Spoof Data Hash", "Veri Hash'ini Taklit Et"},
			{"Spoof Matchmaking Region", "Eşleşme Bölgesini Taklit Et"},
			{"Spray LS Tag", "LS Etiketini Püskürt"},
			{"Staff Key Card", "Personel Anahtar Kartı"},
			{"Stand On Vehicles", "Araçların Üstünde Dur"},
			{"Street Dealer", "Sokak Satıcısı"},
			{"Suicide", "İntihar"},
			{"Super Jump", "Süper Zıplama"},
			{"Super Run", "Süper Koşu"},
			{"Tactical Equipment", "Taktik Ekipman"},
			{"Take Primary Target", "Birincil Hedefi Al"},
			{"Take Secondary Target", "İkincil Hedefi Al"},
			{"Target Drivers", "Sürücüleri Hedef Al"},
			{"Teleport Backward", "Geriye Işınla"},
			{"Teleport Distance", "Işınlama Mesafesi"},
			{"Teleport Down", "Aşağı Işınla"},
			{"Teleport Forward", "İleri Işınla"},
			{"Teleport Left", "Sola Işınla"},
			{"Teleport Player To Coord", "Oyuncuyu Koordinata Işınla"},
			{"Teleport Right", "Sağa Işınla"},
			{"Teleport to Buried Stash", "Gömülü İstife Işınla"},
			{"Teleport to Dealer", "Satıcıya Işınla"},
			{"Teleport to Exotic Exports Vehicle", "Egzotik İhracat Aracına Işınla"},
			{"Teleport to Golden Clover", "Altın Yoncaya Işınla"},
			{"Teleport to G's Cache", "G'nin Önbelleğine Işınla"},
			{"Teleport to Hidden Cache", "Gizli Önbelleğe Işınla"},
			{"Teleport to IPL", "IPL'ye Işınla"},
			{"Teleport to LS Tag", "LS Etiketine Işınla"},
			{"Teleport to Madrazo Hit", "Madrazo Vuruşuna Işınla"},
			{"Teleport to Madrazo Hit Target", "Madrazo Vuruş Hedefine Işınla"},
			{"Teleport to Objective", "Görev Noktasına Işınla"},
			{"Teleport to Player", "Oyuncuya Işınla"},
			{"Teleport to Product", "Ürüne Işınla"},
			{"Teleport to Shipwreck", "Enkaza Işınla"},
			{"Teleport to Skydive", "Paraşüt Atlayışına Işınla"},
			{"Teleport to Stash House", "Stash House'a Işınla"},
			{"Teleport to Time Trial", "Süre Denemesine Işınla"},
			{"Teleport to Treasure Chest", "Hazine Sandığına Işınla"},
			{"Teleport to Waypoint", "Noktaya Işınla"},
			{"Teleport Up", "Yukarı Işınla"},
			{"Time Trial", "Süre Denemesi"},
			{"Treasure Chest", "Hazine Sandığı"},
			{"Unlimited Oxygen", "Sınırsız Oksijen"},
			{"Unload IPL", "IPL Kaldır"},
			{"Unlock GTA+", "GTA+ Kilidini Aç"},
			{"Unmarked Weapons", "İşaretsiz Silahlar"},
			{"Vehicle", "Araç"},
			{"Vehicle God Mode", "Araç Tanrı Modu"},
			{"Vehicle Model", "Araç Modeli"},
			{"Wanted Slider", "Aranma Sürgüsü"},
			{"Weapon", "Silah"},
			{"Weapon Damage", "Silah Hasarı"},
			{"Weapon Damage Scale", "Silah Hasar Ölçeği"},
			{"Weapon Explosion Radius", "Silah Patlama Yarıçapı"},
			{"Weapon Explosion RadiusScale", "Silah Patlama Yarıçap Ölçeği"},
			{"Weapon Type", "Silah Türü"},
			{"Weather", "Hava Durumu"},

			// ================= COMMAND DESCRIPTIONS =================
			{"Access code", "Erişim kodu"},
			{"All PEDs attack each other.", "Tüm PED'ler birbirine saldırır."},
			{"Allows aimbot to lock on to enemies and other players in vehicles", "Aimbot'un araçlardaki düşmanlara ve diğer oyunculara kilitlenmesini sağlar"},
			{"Allows altering your weapons damage output", "Silahlarının hasar çıktısını değiştirmeni sağlar"},
			{"Allows MP vehicles to be used in SP", "MP araçlarının Hikaye modunda kullanılmasını sağlar"},
			{"Allows the player to change the character's appearance for free", "Oyuncunun karakterin görünümünü ücretsiz değiştirmesini sağlar"},
			{"Allows the player to change the character's gender", "Oyuncunun karakterin cinsiyetini değiştirmesini sağlar"},
			{"Allows you to access gun locker remotely.", "Silah dolabına uzaktan erişmeni sağlar."},
			{"Allows you to access the selected Street Dealer remotely.", "Seçili sokak satıcısına uzaktan erişmeni sağlar."},
			{"Allows you to access your wardrobe remotely.", "Gardırobuna uzaktan erişmeni sağlar."},
			{"Allows you to fly through the map", "Haritada uçarak dolaşmanı sağlar"},
			{"Allows you to join players with rpf mods (or a half installed game).", "rpf modlu (veya yarım kurulu oyunlu) oyunculara katılmanı sağlar."},
			{"Allows you to keep your hats or head gear inside vehicles.", "Araç içinde şapka veya başlıklarını korumanı sağlar."},
			{"Allows you to listen to any radio station on foot with Hotkey Q", "Q tuşuyla yaya haldeyken herhangi bir radyo istasyonunu dinlemeni sağlar"},
			{"Allows you to pause the game in online (local only).", "Çevrimiçi modda oyunu durdurmanı sağlar (yalnızca yerel)."},
			{"Allows you to play any mission solo. Note that some missions might break if there aren't enough players", "Herhangi bir görevi tek başına oynamanı sağlar. Yeterli oyuncu olmazsa bazı görevler bozulabilir"},
			{"Allows you to request your personal vehicles.", "Kişisel araçlarını çağırmanı sağlar."},
			{"Allows you to stay underwater without losing oxygen.", "Oksijenin bitmeden su altında kalmanı sağlar."},
			{"Alpha mail disguise", "Alpha mail kılığı"},
			{"Always have a parachute", "Her zaman paraşütün olsun"},
			{"Annihilator stealth", "Annihilator gizli"},
			{"Annihilator stealth prep", "Annihilator gizli hazırlığı"},
			{"Armored Caracara", "Zırhlı Caracara"},
			{"Armored Caracara prep", "Zırhlı Caracara hazırlığı"},
			{"Attempts to improve join speed by loading host broadcast variables asynchronously. This may cause certain jobs to break, use with caution", "Host yayın değişkenlerini asenkron yükleyerek katılma hızını iyileştirmeye çalışır. Bazı işlerin bozulmasına neden olabilir, dikkatli kullan"},
			{"Automatically enters the PC access code", "PC erişim kodunu otomatik girer"},
			{"Automatically silences all incoming calls", "Gelen tüm aramaları otomatik susturur"},
			{"Automatically teleports you to the waypoint", "Seni noktaya otomatik ışınlar"},
			{"Be invisible", "Görünmez ol"},
			{"Be locally visible while remaining invisible to other players", "Diğer oyunculara görünmez kalırken yerel olarak görünür ol"},
			{"Blocks all incoming damage", "Gelen tüm hasarı engeller"},
			{"Blocks all incoming damage to your current vehicle", "Mevcut aracına gelen tüm hasarı engeller"},
			{"Blows the player up", "Oyuncuyu havaya uçurur"},
			{"Brings the player to you", "Oyuncuyu yanına getirir"},
			{"Business to claim earning from.", "Kazanç alınacak işletme."},
			{"Bypasses all casino region restrictions", "Tüm casino bölgesi kısıtlamalarını aşar"},
			{"Change the region you matchmake in to the specified value", "Eşleşme bölgeni belirtilen değere değiştirir"},
			{"Claims your safe earnings from the selected business.", "Seçili işletmeden kasa kazancını alır."},
			{"Clears all the dirt and blood on you.", "Üzerindeki tüm kiri ve kanı temizler."},
			{"Clears your wanted level", "Aranma seviyeni temizler"},
			{"Collects G's Cache.", "G'nin önbelleğini toplar."},
			{"Collects Shipwreck.", "Enkazı toplar."},
			{"Collects the Golden Clover.", "Altın yoncayı toplar."},
			{"Collects the selected Buried Stash.", "Seçili gömülü istifi toplar."},
			{"Collects the selected Hidden Cache.", "Seçili gizli önbelleği toplar."},
			{"Collects the selected product.", "Seçili ürünü toplar."},
			{"Collects the selected Treasure Chest.", "Seçili hazine sandığını toplar."},
			{"Color of the paint gun", "Boya tabancasının rengi"},
			{"Completes all the Daily Objectives and the Weekly Challenge.", "Tüm Günlük Hedefleri ve Haftalık Meydan Okumayı tamamlar."},
			{"Completes the selected Skydive.", "Seçili paraşüt atlayışını tamamlar."},
			{"Completes the selected Time Trial.", "Seçili süre denemesini tamamlar."},
			{"Cuts display case glass instantly", "Vitrin camını anında keser"},
			{"Cuts the glass", "Camı keser"},
			{"Cuts the sewer", "Kanalizasyonu keser"},
			{"Deletes all objects in the game world, including mission critical objects", "Görev açısından kritik nesneler dahil oyun dünyasındaki tüm nesneleri siler"},
			{"Deletes all peds in the game world, including mission critical peds", "Görev açısından kritik PED'ler dahil oyun dünyasındaki tüm PED'leri siler"},
			{"Deletes all vehicles in the game world, including mission critical vehicles", "Görev açısından kritik araçlar dahil oyun dünyasındaki tüm araçları siler"},
			{"Deletes the vehicle the player is in", "Oyuncunun içindeki aracı siler"},
			{"Desired rocket boost behavior", "İstenen roket boost davranışı"},
			{"Detaches your camera and allows you to go anywhere!", "Kameranı ayırır ve her yere gitmeni sağlar!"},
			{"Directly delivers the next Exotic Exports vehicle.", "Sonraki Egzotik İhracat aracını doğrudan teslim eder."},
			{"Disables death barriers found under the map. This also prevents dying randomly when spectating someone", "Haritanın altındaki ölüm bariyerlerini kapatır. Birini izlerken rastgele ölmeyi de engeller"},
			{"Disables laser security grid", "Lazer güvenlik ızgarasını kapatır"},
			{"Disables the player's janky movement during combat.", "Oyuncunun çatışma sırasındaki dengesiz hareketini kapatır."},
			{"Driver", "Şoför"},
			{"Dumps the current data hash into the console", "Güncel veri hash'ini konsola döker"},
			{"EMP charges prep", "EMP yükleri hazırlığı"},
			{"EMP charges purchased", "Satın alınan EMP yükleri"},
			{"Enables all the DLC vehicles on websites.", "Web sitelerindeki tüm DLC araçlarını etkinleştirir."},
			{"Enables Buried Stashes in Los Santos, so you don't have to go to Cayo Perico.", "Los Santos'ta Gömülü İstifleri etkinleştirir, böylece Cayo Perico'ya gitmene gerek kalmaz."},
			{"Enables custom weapon only when weapon is out", "Özel silahı yalnızca silah eldeyken etkinleştirir"},
			{"Enables rainbow color for paint gun", "Boya tabancası için gökkuşağı rengini etkinleştirir"},
			{"Enables special abilities in multiplayer. This repurposes cut content and may be unstable", "Çok oyunculuda özel yetenekleri etkinleştirir. Kesilmiş içeriği yeniden kullanır ve dengesiz olabilir"},
			{"Enables the developer mode in Creator.", "Yaratıcı'da geliştirici modunu etkinleştirir."},
			{"Enables Treasure Chests in Los Santos, so you don't have to go to Cayo Perico.", "Los Santos'ta Hazine Sandıklarını etkinleştirir, böylece Cayo Perico'ya gitmene gerek kalmaz."},
			{"Ensures that the special ability bar never runs out", "Özel yetenek çubuğunun asla boşalmamasını sağlar"},
			{"Enters the last vehicle you were in", "İçinde olduğun son araca biner"},
			{"Enters the Stash House safe code.", "Stash House kasa kodunu girer."},
			{"Every bullet you shoot explodes.", "Ateşlediğin her mermi patlar."},
			{"Features", "Özellikler"},
			{"Fills all of your snacks and armours.", "Tüm atıştırmalıklarını ve zırhlarını doldurur."},
			{"Fixes all of your destroyed personal vehicles.", "Yok edilen tüm kişisel araçlarını onarır."},
			{"Fixes any damage to your current vehicle", "Mevcut araçtaki hasarı onarır"},
			{"Forces all players to be ready", "Tüm oyuncuları hazır olmaya zorlar"},
			{"Forces player into permadeath that can only be fixed by a game restart", "Oyuncuyu yalnızca oyunu yeniden başlatarak düzeltilebilen kalıcı ölüme zorlar"},
			{"Forces the player into an infinite loading screen that can only be fixed by restarting the game", "Oyuncuyu yalnızca oyunu yeniden başlatarak düzeltilebilen sonsuz yükleme ekranına zorlar"},
			{"Forces the specified weather. Note that this effect is local and cannot be seen by other players", "Belirtilen havayı zorlar. Bu etki yereldir ve diğer oyuncular tarafından görülemez"},
			{"Forces the weather to thunder for all players in the session", "Oturumdaki tüm oyuncular için havayı gök gürültülü yapmaya zorlar"},
			{"Forces you to become freemode script host. Note that this might break some missions.", "Seni freemode script host olmaya zorlar. Bazı görevleri bozabilir."},
			{"Force-unlocks GTA+ content. Use with caution", "GTA+ içeriğini zorla kilidini açar. Dikkatli kullan"},
			{"Formats HUD money with commas.", "HUD parasını virgülle biçimlendirir."},
			{"Freeze your wanted level to the desired level", "Aranma seviyeni istediğin seviyede dondurur"},
			{"Freezes the online clock at the selected time", "Çevrimiçi saati seçili zamanda dondurur"},
			{"Gives all weapons to the player", "Oyuncuya tüm silahları verir"},
			{"Gives you all weapons", "Sana tüm silahları verir"},
			{"Glass cutter prep", "Cam kesici hazırlığı"},
			{"Glass cutter purchased", "Satın alınan cam kesici"},
			{"Guard routes prep", "Devriye rotaları hazırlığı"},
			{"Guard routes purchased", "Satın alınan devriye rotaları"},
			{"Guard shipments", "Sevkiyatları koru"},
			{"Gunman", "Silahlı adam"},
			{"Hacker", "Hacker"},
			{"Hacking device", "Hack cihazı"},
			{"Have an endless clip in your gun", "Silahında sonsuz şarjör olsun"},
			{"Hazmat suit", "Koruyucu takım"},
			{"Heist approach", "Soygun yaklaşımı"},
			{"Heist categories", "Soygun kategorileri"},
			{"Heist difficulty", "Soygun zorluğu"},
			{"Hides you from other players on the radar", "Seni diğer oyuncuların radarından gizler"},
			{"How fast the freecam will move positions", "Serbest kameranın ne kadar hızlı hareket edeceği"},
			{"Increases the fire rate of your weapons substantially", "Silahlarının atış hızını önemli ölçüde artırır"},
			{"Instantly passes Doomsday Scenario Act: III", "Kıyamet Senaryosu Perde: III'ü anında geçer"},
			{"Instantly passes Pacific Standard Job", "Pacific Standard görevini anında geçer"},
			{"Instantly passes the heist", "Soygunu anında geçer"},
			{"Joins the specified session type", "Belirtilen oturum türüne katılır"},
			{"JUL", "TEM"},
			{"Jump higher than normal", "Normalden daha yükseğe zıpla"},
			{"Keeps the player clean from any blood, dirt, water.", "Oyuncuyu kandan, kirden ve sudan temiz tutar."},
			{"Keeps your vehicle clean and fixed", "Aracını temiz ve sağlam tutar"},
			{"Kicks the player by faking a vote kick", "Sahte oylama atması yaparak oyuncuyu atar"},
			{"Kicks the player by forcing them to call a null script function", "Null script fonksiyonu çağırmaya zorlayarak oyuncuyu atar"},
			{"Kicks the player by forcing them to end the freemode session", "Freemode oturumunu bitirmeye zorlayarak oyuncuyu atar"},
			{"Kicks the player from their organization or motorcycle club", "Oyuncuyu organizasyonundan veya motosiklet kulübünden atar"},
			{"Kills all enemies in the game world", "Oyun dünyasındaki tüm düşmanları öldürür"},
			{"Kills all peds in the game world", "Oyun dünyasındaki tüm PED'leri öldürür"},
			{"Kills the player", "Oyuncuyu öldürür"},
			{"Kills you", "Seni öldürür"},
			{"Launches entity when released", "Bırakıldığında varlığı fırlatır"},
			{"Lets you win the Rig Slot Machines every time", "Rig Slot Makinelerinde her seferinde kazanmanı sağlar"},
			{"Load IPL", "IPL yükle"},
			{"Locks on to enemies and other players", "Düşmanlara ve diğer oyunculara kilitlenir"},
			{"Lowers your current vehicle's stance. Only some vehicles are supported", "Mevcut aracının yüksekliğini düşürür. Yalnızca bazı araçlar desteklenir"},
			{"Makes the vehicle boost when you hold the horn", "Kornaya bastığında aracın boost yapmasını sağlar"},
			{"Manchez", "Manchez"},
			{"Manchez prep", "Manchez hazırlığı"},
			{"Matchmaking region to spoof to", "Taklit edilecek eşleşme bölgesi"},
			{"Matchmaking will put you into sessions with other YimMenu users.", "Eşleşme seni diğer YimMenu kullanıcılarıyla oturumlara koyar."},
			{"Model of the vehicle", "Aracın modeli"},
			{"Modifies weapon ability", "Silah yeteneğini değiştirir"},
			{"Modify rocket boost behavior for vehicles that support it", "Destekleyen araçlar için roket boost davranışını değiştirir"},
			{"Modifying Weapon Explosion Radius", "Silah Patlama Yarıçapını değiştirir"},
			{"Modifying Weapon Explosion RadiusScale", "Silah Patlama Yarıçap Ölçeğini değiştirir"},
			{"Multipler for base run/sprint speed", "Temel koş/koşuştur hızı için çarpan"},
			{"Multipler with which the run/sprint/swim speed is increased with until maximum speed is reached", "Maksimum hıza ulaşılana kadar koş/koşuştur/yüz hızının artırıldığı çarpan"},
			{"Multiplies RP by the given value", "RP'yi verilen değerle çarpar"},
			{"Nearby peds will ignore you and become oblivious to your actions.", "Yakındaki PED'ler seni yok sayar ve eylemlerine karşı duyarsızlaşır."},
			{"NEED", "GEREKLİ"},
			{"Never gain a wanted level", "Asla aranma seviyesi kazanma"},
			{"Only available as host and the target is unblockable", "Yalnızca host olarak kullanılabilir ve hedef engellenemez"},
			{"Photographs the selected animal.", "Seçili hayvanı fotoğraflar."},
			{"Player 1 cut", "Oyuncu 1 payı"},
			{"Player 2 cut", "Oyuncu 2 payı"},
			{"Player 3 cut", "Oyuncu 3 payı"},
			{"Player 4 cut", "Oyuncu 4 payı"},
			{"Power drills prep", "Güç matkapları hazırlığı"},
			{"Power drills purchased", "Satın alınan güç matkapları"},
			{"Prevent you from getting Critical Hits", "Kritik vuruş almanı engeller"},
			{"Prevents you from being kicked while idling.", "Boşta kalırken atılmanı engeller."},
			{"Prevents you from falling out of vehicles.", "Araçlardan düşmeni engeller."},
			{"Prevents you from ragdolling when standing on top of vehicles.", "Araçların üzerinde dururken ragdoll olmanı engeller."},
			{"Prevents your ped from ragdolling", "PED'inin ragdoll olmasını engeller"},
			{"Primary target", "Birincil hedef"},
			{"Refills your ammo to max.", "Mermilerini maksimuma doldurur."},
			{"Removes Los Santos Customs vehicle modification restrictions", "Los Santos Customs araç modifikasyon kısıtlamalarını kaldırır"},
			{"Removes the cooldown for changing appearance", "Görünüm değiştirme beklemesini kaldırır"},
			{"Requests your current Personal Vehicle.", "Mevcut kişisel aracını çağırır."},
			{"Restores your health and armour.", "Sağlığını ve zırhını geri kazandırır."},
			{"Returns your current Personal Vehicle to storage.", "Mevcut kişisel aracını depoya geri götürür."},
			{"RP Mulitplier (< 0 = 0 -> No RP)", "RP Çarpanı (< 0 = 0 -> RP Yok)"},
			{"Run faster than normal", "Normalden daha hızlı koş"},
			{"Saves the current vehicle you are in as your personal vehicle.", "İçinde olduğun aracı kişisel aracın olarak kaydeder."},
			{"Scope out Kortz Center", "Kortz Center'ı incele"},
			{"Scope points of interest", "İlgi noktalarını incele"},
			{"Scope secondary targets", "İkincil hedefleri incele"},
			{"Selected Animal", "Seçili Hayvan"},
			{"Selected Buried Stash", "Seçili Gömülü İstif"},
			{"Selected Hidden Cache", "Seçili Gizli Önbellek"},
			{"Selected LS Tag", "Seçili LS Etiketi"},
			{"Selected Product", "Seçili Ürün"},
			{"Selected Skydive", "Seçili Paraşüt Atlayışı"},
			{"Selected Street Dealer", "Seçili Sokak Satıcısı"},
			{"Selected Time Trial", "Seçili Süre Denemesi"},
			{"Selected Treasure Chest", "Seçili Hazine Sandığı"},
			{"Sends a random sext to the specified player", "Belirtilen oyuncuya rastgele bir sext gönderir"},
			{"Sends the Gooch to the specified player.", "Belirtilen oyuncuya Gooch'u gönderir."},
			{"Sends the Phantom Car to the specified player.", "Belirtilen oyuncuya Hayalet Aracı gönderir."},
			{"Sends the player to the selected interior", "Oyuncuyu seçili iç mekâna gönderir"},
			{"Sends the player to the selected property", "Oyuncuyu seçili mülke gönderir"},
			{"Set hour (0-23)", "Saat ayarla (0-23)"},
			{"Set minute (0-59)", "Dakika ayarla (0-59)"},
			{"Set second (0-59)", "Saniye ayarla (0-59)"},
			{"Sets heist cut", "Soygun payını ayarlar"},
			{"Sets the bounty as anonymous", "Ödülü anonim olarak ayarlar"},
			{"Sets the current online time", "Güncel çevrimiçi saati ayarlar"},
			{"Sets the damage scale for weapons (including melee)", "Silahlar için hasar ölçeğini ayarlar (yakın dövüş dahil)"},
			{"Sets the specifed weather. Note that this effect is local and cannot be seen by other players", "Belirtilen havayı ayarlar. Bu etki yereldir ve diğer oyuncular tarafından görülemez"},
			{"Sets the specified bounty to the player", "Belirtilen ödülü oyuncuya koyar"},
			{"Sets up cayo perico heist", "Cayo Perico soygununu kurar"},
			{"Sets up current apartment heist", "Güncel daire soygununu kurar"},
			{"Sets up diamond casino heist", "Elmas casino soygununu kurar"},
			{"Sets up doomsday heist", "Kıyamet soygununu kurar"},
			{"Sets up Kortz Center heist", "Kortz Center soygununu kurar"},
			{"Sets your wanted level to the desired level", "Aranma seviyeni istediğin seviyeye ayarlar"},
			{"Shows a speedometer whenever you are in a vehicle", "Araçtayken hız göstergesi gösterir"},
			{"Skips any currently playing cutscene", "Oynatılan herhangi bir sahneyi atlar"},
			{"Skips card swiping process", "Kart çekme işlemini atlar"},
			{"Skips current conversation in the phone.", "Telefondaki güncel konuşmayı atlar."},
			{"Skips data crack minigame", "Veri kırma mini oyununu atlar"},
			{"Skips drilling process", "Delme işlemini atlar"},
			{"Skips fingerprint hacking minigame in computer room", "Bilgisayar odasındaki parmak izi hack mini oyununu atlar"},
			{"Skips hacking process", "Hack işlemini atlar"},
			{"Skips signal nodes hacking at vault keypad", "Kasa tuş takımındaki sinyal düğümü hack'ini atlar"},
			{"Spams the killfeed of all players with fake kill entries. Use with caution", "Tüm oyuncuların killfeed'ini sahte öldürme kayıtlarıyla spamlar. Dikkatli kullan"},
			{"Spawns a ped at your current location.", "Mevcut konumuna bir PED doğurur."},
			{"Spawns an object at your current location.", "Mevcut konumuna bir nesne doğurur."},
			{"Spawns the selected animal.", "Seçili hayvanı doğurur."},
			{"Spectates the selected player", "Seçili oyuncuyu izler"},
			{"Speed of rainbow color for paint gun", "Boya tabancası için gökkuşağı rengi hızı"},
			{"Spoofs your position to make it appear as if you're next to all the players in the session at all times. Use with caution", "Konumunu taklit ederek her an oturumdaki tüm oyuncuların yanındaymış gibi görünmeni sağlar. Dikkatli kullan"},
			{"Sprays the selected LS Tag.", "Seçili LS etiketini püskürtür."},
			{"Staff key card", "Personel anahtar kartı"},
			{"Style of rainbow color for paint gun", "Boya tabancası için gökkuşağı rengi stili"},
			{"Switch session to apply the changes.", "Değişiklikleri uygulamak için oturumu değiştir."},
			{"Tactical equipment", "Taktik ekipman"},
			{"Takes primary target", "Birincil hedefi alır"},
			{"Takes primary target painting (stand near it)", "Birincil hedef tablosunu alır (yanında dur)"},
			{"Takes secondary loot (stand near it)", "İkincil ganimeti alır (yanında dur)"},
			{"Targets the head when locking on to enemies and other players", "Düşmanlara ve diğer oyunculara kilitlenirken kafayı hedefler"},
			{"Teleport to the selected IPL", "Seçili IPL'ye ışınlan"},
			{"Teleportation distance of directional teleports", "Yönsel ışınlamaların ışınlanma mesafesi"},
			{"Teleports all game objects to you", "Oyun dünyasındaki tüm nesneleri sana ışınlar"},
			{"Teleports all game peds to you", "Oyun dünyasındaki tüm PED'leri sana ışınlar"},
			{"Teleports all game vehicles to you", "Oyun dünyasındaki tüm araçları sana ışınlar"},
			{"Teleports the player to the specified coordinates", "Oyuncuyu belirtilen koordinatlara ışınlar"},
			{"Teleports to G's Cache.", "G'nin önbelleğine ışınlar."},
			{"Teleports to Madrazo Hit Target.", "Madrazo Vuruş Hedefine ışınlar."},
			{"Teleports to Madrazo Hit.", "Madrazo Vuruşuna ışınlar."},
			{"Teleports to Shipwreck.", "Enkaza ışınlar."},
			{"Teleports to Stash House.", "Stash House'a ışınlar."},
			{"Teleports to the Golden Clover.", "Altın yoncaya ışınlar."},
			{"Teleports to the next Exotic Exports vehicle.", "Sonraki Egzotik İhracat aracına ışınlar."},
			{"Teleports to the selected Buried Stash.", "Seçili gömülü istife ışınlar."},
			{"Teleports to the selected Hidden Cache.", "Seçili gizli önbelleğe ışınlar."},
			{"Teleports to the selected LS Tag.", "Seçili LS etiketine ışınlar."},
			{"Teleports to the selected product.", "Seçili ürüne ışınlar."},
			{"Teleports to the selected Skydive.", "Seçili paraşüt atlayışına ışınlar."},
			{"Teleports to the selected Street Dealer.", "Seçili sokak satıcısına ışınlar."},
			{"Teleports to the selected Time Trial.", "Seçili süre denemesine ışınlar."},
			{"Teleports to the selected Treasure Chest.", "Seçili hazine sandığına ışınlar."},
			{"Teleports you backward", "Seni geriye ışınlar"},
			{"Teleports you down", "Seni aşağı ışınlar"},
			{"Teleports you forward", "Seni ileri ışınlar"},
			{"Teleports you to the left", "Seni sola ışınlar"},
			{"Teleports you to the Objective", "Seni görev noktasına ışınlar"},
			{"Teleports you to the right", "Seni sağa ışınlar"},
			{"Teleports you to the selected player", "Seni seçili oyuncuya ışınlar"},
			{"Teleports you to the waypoint", "Seni noktaya ışınlar"},
			{"Teleports you up", "Seni yukarı ışınlar"},
			{"The bounty amount to set", "Ayarlanacak ödül miktarı"},
			{"The coordinates to teleport the player to", "Oyuncunun ışınlanacağı koordinatlar"},
			{"The IPL to load", "Yüklenecek IPL"},
			{"The interior index to send the player(s) to", "Oyuncunun(ların) gönderileceği iç mekân indeksi"},
			{"The model name of the object you wish to spawn.", "Doğurmak istediğin nesnenin model adı."},
			{"The model name of the ped you wish to spawn.", "Doğurmak istediğin PED'in model adı."},
			{"The property index to send the player(s) to", "Oyuncunun(ların) gönderileceği mülk indeksi"},
			{"The session type to join", "Katılınacak oturum türü"},
			{"The special ability to enable for the MP character", "MP karakteri için etkinleştirilecek özel yetenek"},
			{"The type of custom weapon to use", "Kullanılacak özel silah türü"},
			{"Unload IPL", "IPL kaldır"},
			{"Unmarked weapons", "İşaretsiz silahlar"},
			{"Updates actual take", "Güncel payı günceller"},
			{"Updates potential take", "Potansiyel payı günceller"},
			{"Updates primary target value", "Birincil hedef değerini günceller"},
			{"Updates secondary take value", "İkincil pay değerini günceller"},
			{"Use this to clear the chat", "Sohbeti temizlemek için kullan"},
			{"Use this to open the chat", "Sohbeti açmak için kullan"},
			{"Vehicle", "Araç"},
			{"Wanted level to set/freeze", "Ayarlanacak/dondurulacak aranma seviyesi"},
			{"Weapon", "Silah"},
			{"Weapon category", "Silah kategorisi"},
			{"Weather to set or force. Note that this is local and cannot be seen by other players", "Ayarlanacak veya zorlanacak hava durumu. Bu yereldir ve diğer oyuncular tarafından görülemez"},
			{"When you are wanted, no police will be spawned.", "Aranırken polis doğurulmaz."},
			{"You will never run out of ammo", "Mermin asla tükenmeyecek"},
			{"You won't die because of border restrictions.", "Sınır kısıtlamaları yüzünden ölmeyeceksin."},

			// ================= SUBMENUS =================
			{"Debug", "Hata Ayıklama"},
			{"Network", "Ağ"},
			{"Players", "Oyuncular"},
			{"Recovery", "Kurtarma"},
			{"Self", "Kendim"},
			{"Settings", "Ayarlar"},
			{"Teleport", "Işınlanma"},
			{"Vehicle", "Araç"},
			{"World", "Dünya"},

			// ================= CATEGORIES =================
			{"Businesses", "İşletmeler"},
			{"Casino", "Casino"},
			{"Customize", "Özelleştir"},
			{"Daily Activities", "Günlük Aktiviteler"},
			{"Game", "Oyun"},
			{"GUI", "Arayüz"},
			{"Heists", "Soygunlar"},
			{"Hotkeys", "Kısayollar"},
			{"Info", "Bilgi"},
			{"IPLs", "IPL'ler"},
			{"Kick", "Atma"},
			{"Lua Scripts", "Lua Betikleri"},
			{"Main", "Ana"},
			{"Outfit Editor", "Kıyafet Düzenleyici"},
			{"Random Events", "Rastgele Olaylar"},
			{"Saved", "Kayıtlı"},
			{"Saved Players", "Kayıtlı Oyuncular"},
			{"Saved Vehicles", "Kayıtlı Araçlar"},
			{"Session", "Oturum"},
			{"Spawn", "Doğurma"},
			{"Spawn Ped", "PED Doğur"},
			{"Spoofing", "Taklit"},
			{"Stat Editor", "Stat Düzenleyici"},
			{"Toxic", "Zehirli"},
			{"Transactions", "İşlemler"},
			{"Troll", "Troll"},
			{"Vehicle Editor", "Araç Düzenleyici"},
			{"Weapons", "Silahlar"},

			// ================= GROUPS =================
			{"Aimbot", "Aimbot"},
			{"Ammu-Nation", "Ammu-Nation"},
			{"Blackjack", "Blackjack"},
			{"Bounty", "Ödül"},
			{"Bring", "Getir"},
			{"Chat", "Sohbet"},
			{"Custom Weapons", "Özel Silahlar"},
			{"Damage", "Hasar"},
			{"Delete", "Sil"},
			{"Enhancements", "Geliştirmeler"},
			{"From Clipboard", "Panodan"},
			{"General", "Genel"},
			{"Globals", "Genel"},
			{"Griefing", "Griefing"},
			{"Heist Cuts", "Soygun Payları"},
			{"Heist Setups", "Soygun Kurulumları"},
			{"In-Heist", "Soygun İçi"},
			{"Join", "Katıl"},
			{"Kicks", "Atmalar"},
			{"Kill", "Öldür"},
			{"Loots", "Ganimetler"},
			{"Lucky Wheel", "Şanslı Çark"},
			{"Matchmaking (Client)", "Eşleşme (İstemci)"},
			{"Matchmaking (Server)", "Eşleşme (Sunucu)"},
			{"Misc", "Çeşitli"},
			{"Movement", "Hareket"},
			{"New", "Yeni"},
			{"Notifications", "Bildirimler"},
			{"Object ESP", "Nesne ESP"},
			{"Other", "Diğer"},
			{"Overlay", "Overlay"},
			{"Packed", "Paketli"},
			{"Packed Range", "Paketli Aralık"},
			{"Ped ESP", "PED ESP"},
			{"Player ESP", "Oyuncu ESP"},
			{"Primary Target", "Birincil Hedef"},
			{"Regular", "Normal"},
			{"Roulette", "Rulet"},
			{"Slot Machines", "Slot Makineleri"},
			{"Special Ability", "Özel Yetenek"},
			{"Teleport", "Işınlanma"},
			{"Time", "Zaman"},
			{"Tools", "Araçlar"},
			{"Tracking", "Takip"},
			{"Triggerer", "Tetikleyici"},
			{"UI", "Arayüz"},
			{"Wanted", "Aranma"},
			{"Weather", "Hava Durumu"},

			// ================= ITEM LABEL OVERRIDES =================
			{"Amount", "Miktar"},
			{"Anonymous", "Anonim"},
			{"Auto Update", "Otomatik Güncelle"},
			{"Bring All", "Hepsini Getir"},
			{"CEO Kick All", "Tüm CEO'ları At"},
			{"Delete Player Vehicles", "Oyuncu Araçlarını Sil"},
			{"Enable in MP", "MP'de Etkinleştir"},
			{"Explode All", "Hepsini Patlat"},
			{"Freeze", "Dondur"},
			{"Godmode", "Tanrı Modu"},
			{"Host Kick All", "Tüm Hostları At"},
			{"Keep Fixed", "Sağlam Tut"},
			{"Kill All", "Hepsini Öldür"},
			{"Level", "Seviye"},
			{"Lower Stance", "Yüksekliği Düşür"},
			{"Minute", "Dakika"},
			{"Object Distance", "Nesne Mesafesi"},
			{"Object Net Info", "Nesne Ağ Bilgisi"},
			{"Object Script Info", "Nesne Betik Bilgisi"},
			{"Ped Distance", "PED Mesafesi"},
			{"Ped Hashes", "PED Hash'leri"},
			{"Ped Net Info", "PED Ağ Bilgisi"},
			{"Ped Script Info", "PED Betik Bilgisi"},
			{"Ped Skeleton", "PED İskeleti"},
			{"Permadeath All", "Hepsini Kalıcı Ölüme At"},
			{"Player Distance", "Oyuncu Mesafesi"},
			{"Player Name", "Oyuncu Adı"},
			{"Player Skeleton", "Oyuncu İskeleti"},
			{"Second", "Saniye"},
			{"Send All to Interior", "Hepsini İç Mekâna Gönder"},
			{"Send All to Property", "Hepsini Mülke Gönder"},
			{"Send Sexts", "Sext Gönder"},
			{"Session Type", "Oturum Türü"},
			{"Set", "Ayarla"},
			{"Set Bounties", "Ödüller Koy"},
			{"Spoof Region", "Bölgeyi Taklit Et"},
			{"Teleport", "Işınla"},
			{"Teleport Everyone", "Herkesi Işınla"},
			{"Teleport To", "Şuna Işınla"},
			{"Tracking Notifications", "Takip Bildirimleri"},
			{"Update Now", "Şimdi Güncelle"},

			// ================= LIST OPTIONS =================
			{"Classic", "Klasik"},
			{"Modern", "Modern"},
			{"Modern (Vertical)", "Modern (Dikey)"},
			{"Modern (Modular)", "Modern (Modüler)"},

			// ================= EXTRA COMMAND LABELS =================
			{"Notify On Job Lobby Change", "İş Lobisi Değişimini Bildir"},
			{"Notify On Mission Change", "Görev Değişimini Bildir"},
			{"Notify On Session Type Change", "Oturum Türü Değişimini Bildir"},
			{"Notify When Joinable", "Katılabilir Olunca Bildir"},
			{"Notify When Offline", "Çevrimdışı Olunca Bildir"},
			{"Notify When Online", "Çevrimiçi Olunca Bildir"},
			{"Notify When Unjoinable", "Katılınamaz Olunca Bildir"},
			{"Notify on Player Join", "Oyuncu Katılınca Bildir"},
			{"Explosion Camera Shake", "Patlama Kamera Sarsıntısı"},
			{"Explosion Damage Scale", "Patlama Hasar Ölçeği"},
			{"Explosion Type", "Patlama Türü"},
			{"Melee Damage", "Yakın Dövüş Hasarı"},
			{"Melee Damage Scale", "Yakın Dövüş Hasar Ölçeği"},
			{"UI Style", "Arayüz Stili"},
			{"Scripts", "Betikler"},
			{"Threads", "İş Parçacıkları"},
			{"Thread", "İş Parçacığı"},
			{"Start Script", "Betiği Başlat"},
			{"Stack Size", "Yığın Boyutu"},
			{"Player Database Auto Update", "Oyuncu Veritabanı Otomatik Güncelleme"},
			{"Release Dead Target", "Ölü Hedefi Bırak"},
			{"Spawn Clone", "Klon Doğur"},
			{"Spawn Inside", "İçine Doğur"},
			{"Spawn Maxed", "Maksimumlu Doğur"},
			{"Update Saved Players Now", "Kayıtlı Oyuncuları Şimdi Güncelle"},
			{"New Vehicle", "Yeni Araç"},
			{"Personal Vehicle", "Kişisel Araç"},
			{"Locals", "Yereller"},
			{"Editor", "Düzenleyici"},
			{"Random Events", "Rastgele Olaylar"},

			// ================= EXTRA COMMAND DESCRIPTIONS =================
			{"Notifies you when a tracked player joins or leaves a job lobby", "Takip edilen bir oyuncu iş lobisine katıldığında veya ayrıldığında bildirir"},
			{"Notifies you when a tracked player joins or leaves a mission", "Takip edilen bir oyuncu göreve katıldığında veya ayrıldığında bildirir"},
			{"Notifies you when a tracked player's session type changes", "Takip edilen bir oyuncunun oturum türü değiştiğinde bildirir"},
			{"Notifies you when a tracked player becomes joinable", "Takip edilen bir oyuncu katılabilir olduğunda bildirir"},
			{"Notifies you when a tracked player goes offline", "Takip edilen bir oyuncu çevrimdışı olduğunda bildirir"},
			{"Notifies you when a tracked player goes online", "Takip edilen bir oyuncu çevrimiçi olduğunda bildirir"},
			{"Notifies you when a tracked player becomes unjoinable", "Takip edilen bir oyuncu katılınamaz olduğunda bildirir"},
			{"Automatically updates tracked player status every 3 minutes. This is required for tracking notifications to work", "Takip edilen oyuncu durumunu her 3 dakikada bir otomatik günceller. Takip bildirimlerinin çalışması için gereklidir"},
			{"Releases the lock-on to the target after they are dead", "Hedef öldükten sonra hedefe kilitlenmeyi bırakır"},
			{"Spawn a clone of the persone vehicle.", "Kişisel aracın bir klonunu doğurur."},
			{"Spawn inside the personal vehicle.", "Kişisel aracın içine doğur."},
			{"Spawn inside the vehicle.", "Aracın içine doğur."},
			{"Spawn the vehicle maxed.", "Aracı tam donanımlı doğur."},
			{"Notifies you when the state of a player you track changes", "Takip ettiğin bir oyuncunun durumu değiştiğinde bildirir"},
			{"Allows altering your melee damage output", "Yakın dövüş hasar çıktını değiştirmeni sağlar"},
			{"Choose the UI style", "Arayüz stilini seç"},
			{"Controls how much the camera shakes during explosions", "Patlamalar sırasında kameranın ne kadar sarsılacağını kontrol eder"},
			{"Notifies you when a player joins above the map", "Haritanın üstünde bir oyuncu katıldığında bildirir"},
			{"Select an explosion type", "Bir patlama türü seç"},
			{"Sets the damage scale for explosions", "Patlamalar için hasar ölçeğini ayarlar"},
			{"Sets the damage scale for melee", "Yakın dövüş için hasar ölçeğini ayarlar"},

			// ================= GUI SETTINGS PRETTY LABELS =================
			{"Window Rounding", "Pencere Köşe Eğriliği"},
			{"Frame Rounding", "Çerçeve Köşe Eğriliği"},
			{"Grab Rounding", "Tutma Köşe Eğriliği"},
			{"Scrollbar Rounding", "Kaydırma Çubuğu Köşe Eğriliği"},
			{"Child Rounding", "Alt Pencere Köşe Eğriliği"},
			{"Popup Rounding", "Açılır Pencere Köşe Eğriliği"},
			{"Tab Rounding", "Sekme Köşe Eğriliği"},
			{"Window Padding Horizontal", "Pencere İç Boşluğu Yatay"},
			{"Window Padding Vertical", "Pencere İç Boşluğu Dikey"},
			{"Item Spacing Horizontal", "Öğe Boşluğu Yatay"},
			{"Item Spacing Vertical", "Öğe Boşluğu Dikey"},
			{"Item Inner Spacing Horizontal", "Öğe İç Boşluğu Yatay"},
			{"Item Inner Spacing Vertical", "Öğe İç Boşluğu Dikey"},
			{"Touch Extra Padding Horizontal", "Dokunma Ekstra Dolgusu Yatay"},
			{"Touch Extra Padding Vertical", "Dokunma Ekstra Dolgusu Dikey"},
			{"Display Safe Area Padding Horizontal", "Güvenli Alan Dolgusu Yatay"},
			{"Display Safe Area Padding Vertical", "Güvenli Alan Dolgusu Dikey"},
			{"Indent Spacing", "Girinti Boşluğu"},
			{"Columns Min Spacing", "Sütun Min. Boşluğu"},
			{"Window Title Align Horizontal", "Pencere Başlık Hizası Yatay"},
			{"Window Title Align Vertical", "Pencere Başlık Hizası Dikey"},
			{"Button Text Align Horizontal", "Buton Yazı Hizası Yatay"},
			{"Button Text Align Vertical", "Buton Yazı Hizası Dikey"},
			{"Selectable Text Align Horizontal", "Seçilebilir Yazı Hizası Yatay"},
			{"Selectable Text Align Vertical", "Seçilebilir Yazı Hizası Dikey"},
			{"Window Border Size", "Pencere Kenarlık Boyutu"},
			{"Frame Border Size", "Çerçeve Kenarlık Boyutu"},
			{"Tab Border Size", "Sekme Kenarlık Boyutu"},
			{"Popup Border Size", "Açılır Pencere Kenarlık Boyutu"},
			{"Global Alpha", "Genel Saydamlık"},
			{"Disabled Alpha", "Pasif Saydamlık"},
			{"Mouse Cursor Scale", "Fare İmleci Ölçeği"},
			{"Curve Tessellation Tol", "Eğri Dokulama Toleransı"},
		};

		return map;
	}

	std::string tr(const std::string& key)
	{
		const auto& map = GetLocalizationMap();
		auto it = map.find(key);
		if (it != map.end())
			return it->second;
		return key;
	}
}
